# Use the official Python image as a parent image
FROM python:3.12.0

# Set environment variables
ENV PYTHONDONTWRITEBYTECODE 1
ENV PYTHONUNBUFFERED 1

# Set the working directory in the container
WORKDIR /app

# Install dependencies
COPY requirments.txt /app/
RUN pip install --no-cache-dir -r  requirments.txt
RUN apt-get update && apt-get install -y gettext


# Copy the project code into the container
COPY . /app/

# generate translation file
# RUN python manage.py makemessages -l fa

# Run makemigrations and migrate commands when the container starts
CMD python manage.py makemigrations && python manage.py migrate && python manage.py runserver 0.0.0.0:8000
# CMD python manage.py runserver 0.0.0.0:8000